version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db  
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:root@mysql_db:3306/test_api_login
    volumes:
      - .:/app
    command: ["./wait-for-it.sh", "mysql_db:3306", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]  # Sử dụng mysql_db thay vì db

  mysql_db:
    image: mysql:8
    container_name: mysql_db  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_api_login
    ports:
      - "3307:3306"

